name: Emeris
description: Emeris mobile app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sacco:
    git:
      url: https://github.com/wal33d006/sacco.dart.git
      ref: account-url-fix
  http: 0.13.3
  intl: 0.17.0
  clipboard: 0.1.3
  flutter_secure_storage: 4.2.0
  shared_preferences: 2.0.6
  encrypt: 5.0.0
  web3dart: 2.1.4
  bip39: 1.0.6
  get_it: 7.1.3
  dartz: 0.10.0-nullsafety.2
  mobx: 2.0.1
  decimal: 1.3.0
  flutter_mobx: 2.0.0
  dio: 4.0.0
  wallet_core:
    git:
      url: https://github.com/wal33d006/wallet_core.git
  equatable: 2.0.3
  uuid: 3.0.4
  transaction_signing_gateway:
    git:
      url: https://github.com/tendermint/flutter.git
      path: packages/transaction_signing_gateway
      ref: main


  cupertino_icons: 1.0.3

dependency_overrides:
  pointycastle: 3.0.1 #newer version has problems with web version of app

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true
  generate: true
