name: flutter_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: 0.13.3
  intl: 0.17.0
  clipboard: 0.1.3
  shared_preferences: 2.0.8
  web3dart: 2.3.1
  get_it: 7.2.0
  mobx: 2.0.4
  decimal: 1.3.0
  flutter_mobx: 2.0.2
  dio: 4.0.0
  alan: 0.40.2+1
  biometric_storage: 3.0.1
  crypto: 3.0.1
  pinput: 1.2.0
  wallet_core:
    git:
      url: https://github.com/wal33d006/wallet_core.git
  equatable: 2.0.3
  uuid: 3.0.4
  transaction_signing_gateway:
    git:
      url: https://github.com/tendermint/flutter.git
      path: packages/transaction_signing_gateway
      ref: main
  cosmos_ui_components:
    git:
      url: https://github.com/tendermint/flutter.git
      path: packages/cosmos_ui_components
      ref: main

  cosmos_utils:
    git:
      url: https://github.com/tendermint/flutter.git
      path: packages/cosmos_utils
      ref: main

  cupertino_icons: 1.0.3

dependency_overrides:
  pointycastle: 3.0.1 #newer version has problems with web version of app

## convenient overrides for development to reference packages on local disk, just uncomment following lines and make sure
## it points to the location of the checked out tendermint/flutter repository
#  cosmos_utils:
#    path: ../flutter-public/packages/cosmos_utils
#  transaction_signing_gateway:
#    path: ../flutter-public/packages/transaction_signing_gateway
#  cosmos_ui_components:
#    path: ../flutter-public/packages/transaction_signing_gateway

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: 1.7.2
  mocktail: 0.1.4

flutter:

  uses-material-design: true
  generate: true
