# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :deploy_firebase do
    releaseNotes = changelog_from_git_commits(
        commits_count: 10,
        date_format: "format:%d %b",
        pretty: "- (%cd) %s",
        merge_commit_filtering: "exclude_merges",
        quiet: true
    ).split("\n").select do |elem|
      !elem.include? "skip-ci"
    end[0...5].join("\n")

    print("RELEASE NOTES:\n")
    print(releaseNotes)

    firebase_app_distribution(
        app: ENV["ANDROID_FIREBASE_APP_ID"],
        groups: "android-testers",
        release_notes: releaseNotes,
        apk_path: "../build/app/outputs/flutter-apk/app-profile.apk",
        firebase_cli_token: ENV["FIREBASE_TOKEN"]
    )
  end
end
