name: Flutter Web

on:
  push:
    branches: [deploy-android]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '2.5.1'
  JAVA_VERSION: '12'
  RUBY_VERSION: '2.7'
  LC_ALL: en_US.UTF-8
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  IOS_FIREBASE_APP_ID: ${{ secrets.IOS_FIREBASE_APP_ID }}
  ANDROID_FIREBASE_APP_ID: ${{ secrets.ANDROID_FIREBASE_APP_ID }}
  LANG: en_US.UTF-8

jobs:
  build-android:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: pub get
        run: flutter pub get

      - name: build Android app
        timeout-minutes: 10
        run: flutter build apk --profile --build-number $GITHUB_RUN_NUMBER

      - name: set up ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: deploy firebase Android
        working-directory: ./android
        run: |
          gem install bundler
          bundle install
          bundle exec fastlane deploy_firebase

