name: Deploy Firebase - Android
'on':
  push:
    branches:
      - disabled # TODO reenable it after app is configured in appstoreconnect
  workflow_dispatch: null

concurrency:
  group: '${{ github.head_ref || github.ref }}-android-deployment'
  cancel-in-progress: true

env:
  FLUTTER_VERSION: 2.8.0
  JAVA_VERSION: '12'
  RUBY_VERSION: '2.7'
  ALPHA_ANDROID_FIREBASE_TESTERS_GROUP: android-testers
  LC_ALL: en_US.UTF-8
  MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }} # TODO set in github secrets
  MATCH_APP_ID: ${{ secrets.MATCH_APP_ID }} # TODO set in github secrets
  MATCH_APPLE_USERNAME: ${{ secrets.MATCH_APPLE_USERNAME }} # TODO set in github secrets
  MATCH_TEAM_ID: ${{ secrets.MATCH_TEAM_ID }} # TODO set in github secrets
  MATCH_ITC_TEAM_ID: ${{ secrets.MATCH_ITC_TEAM_ID }} # TODO set in github secrets
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # TODO set in github secrets
  FASTLANE_IOS_CODE_SIGNING_IDENTITY: ${{ secrets.FASTLANE_IOS_CODE_SIGNING_IDENTITY }} # TODO set in github secrets
  MATCH_ADHOC_PROVISIONING_PROFILE: ${{ secrets.MATCH_ADHOC_PROVISIONING_PROFILE }} # TODO set in github secrets
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  FIREBASE_PLIST_FILE: ${{ secrets.FIREBASE_PLIST_FILE }}
  IOS_FIREBASE_APP_ID: ${{ secrets.IOS_FIREBASE_APP_ID }}
  ANDROID_FIREBASE_APP_ID: ${{ secrets.ANDROID_FIREBASE_APP_ID }}
  LANG: en_US.UTF-8

jobs:
  deploy-android:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: pub get
        working-directory: ./ios
        run: flutter pub get

      - name: set up ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: prepare fastlane
        working-directory: ./ios
        run: |
          gem install bundler
          bundle install

      - name: prepare ios build with cosmos testnet
        run: |
          flutter build ios --build-number $GITHUB_RUN_NUMBER --no-codesign --dart-define=LCD_URL=https://api.testnet.cosmos.network --dart-define=LCD_PORT=443 --dart-define=GRPC_URL=https://grpc.testnet.cosmos.network --dart-define=GRPC_PORT=443

      - name: deploy firebase iOS
        working-directory: ./ios
        run: |
          gem install bundler
          bundle install
          bundle exec fastlane deploy_firebase

      - name: Report Status
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_NOTIFICATIONS_CHANNEL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: 'https://github.com/tendermint.png?size=48'
          SLACK_TITLE: Starport Template - DEPLOY FAILED
          SLACK_LINK_NAMES: true
          SLACK_USERNAME: Github iOS Deployment
          MSG_MINIMAL: 'actions url, ref'
          SLACK_FOOTER: Mobile Slackbot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}