name: Deploy Firebase - Android
'on':
  push:
    branches:
      - main
  workflow_dispatch: null

concurrency:
  group: '${{ github.head_ref || github.ref }}-android-deployment'
  cancel-in-progress: true

env:
  FLUTTER_VERSION: '2.8.1'
  JAVA_VERSION: '12'
  RUBY_VERSION: '2.7'
  ALPHA_ANDROID_FIREBASE_TESTERS_GROUP: android-testers
  LC_ALL: en_US.UTF-8
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  ANDROID_FIREBASE_APP_ID: ${{ secrets.ANDROID_FIREBASE_APP_ID }}
  LANG: en_US.UTF-8

jobs:
  deploy-android:
    timeout-minutes: 30
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: pub get
        run: flutter pub get

      - name: set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: prepare fastlane
        working-directory: ./android
        run: |
          gem install bundler
          bundle install

      - name: prepare android build with cosmos testnet
        run: >
          flutter build apk --build-number $GITHUB_RUN_NUMBER
          --profile
          --dart-define=LCD_URL=https://api.testnet.cosmos.network
          --dart-define=LCD_PORT=443
          --dart-define=GRPC_URL=https://grpc.testnet.cosmos.network
          --dart-define=GRPC_PORT=443

      - name: deploy firebase Android
        working-directory: ./android
        run: |
          gem install bundler
          bundle install
          bundle exec fastlane deploy_firebase

      - name: Report Status
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_NOTIFICATIONS_CHANNEL }}
          SLACK_COLOR: '${{ job.status }}'
          SLACK_ICON: 'https://github.com/tendermint.png?size=48'
          SLACK_TITLE: Emeris Android - DEPLOY FAILED
          SLACK_LINK_NAMES: true
          SLACK_USERNAME: Github Android Deployment
          MSG_MINIMAL: 'actions url, ref'
          SLACK_FOOTER: Mobile Slackbot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
