name: Pull Request Worfklow

on: [pull_request]

env:
  FLUTTER_VERSION: '2.2.2'

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
    - name: pub get
      run: flutter pub get

    - name: check codestyle
      run: find lib test -name "*.dart" -not -name "*.g.dart" -not -name "*.freezed.dart" -not -name "*.gen.dart" -exec dartfmt -l 120 --dry-run --set-exit-if-changed {} +;

    - name: dart analysis
      run: flutter analyze

    - name: tests
      run: flutter test

  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
    - name: build Android app
      timeout-minutes: 10
      run: flutter build appbundle
# TODO reenable it when proper development team is set up in app store connect
#  build-ios:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - uses: subosito/flutter-action@v1
#      with:
#        flutter-version: ${{ env.FLUTTER_VERSION }}
#    - name: build Android app
#      run: flutter build appbundle
