name: Pull Request Worfklow

on: [ pull_request ]

env:
  JAVA_VERSION: '12'
  RUBY_VERSION: '2.7'
  LC_ALL: en_US.UTF-8
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  IOS_FIREBASE_APP_ID: ${{ secrets.IOS_FIREBASE_APP_ID }}
  ANDROID_FIREBASE_APP_ID: ${{ secrets.ANDROID_FIREBASE_APP_ID }}
  LANG: en_US.UTF-8

jobs:
  build:
    timeout-minutes: 20
    runs-on: self-hosted
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - uses: kuhnroyal/flutter-fvm-config-action@v1

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: pub get
        run: flutter pub get

      - name: check codestyle
        run: find lib test -name "*.dart" -not -name "*.g.dart" -not -name "*.freezed.dart" -not -name "*.gen.dart" -exec flutter format -l 120 --dry-run --set-exit-if-changed {} +;

      - name: dart analysis
        run: flutter analyze

      - name: generate code coverage files index
        run: make generate_coverage_index_file

      - name: unit tests
        timeout-minutes: 4
        run: flutter test --dart-define=IS_CI=true --coverage --coverage-path=coverage/lcov.info

      - name: read coverage percentage
        run: |
          echo "COVERAGE_THRESHOLD=$(lcov --summary coverage/main.lcov.info | sed -n '3p' | sed -r 's/(.+): (.+)(\%.+)/\2/' | cat)" >> $GITHUB_ENV
          echo $COVERAGE_THRESHOLD

      - uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: './coverage/lcov.info'
          min_coverage: ${{ env.COVERAGE_THRESHOLD }}
          exclude: 'lib/*/*.g.dart lib/generated_assets/*.dart lib/*/*.gen.dart lib/generated_plugin_registrant.dart'

      - uses: vebr/jest-lcov-reporter@v0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./coverage/lcov.info
          lcov-base: ./coverage/main.lcov.info

      - uses: actions/upload-artifact@v2
        name: upload screenshot test failures
        if: failure()
        with:
          name: screenshot-test-failures
          path: test/**/failures/*.png
          if-no-files-found: ignore
          retention-days: 5

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: build Android app
        timeout-minutes: 10
        run: flutter build appbundle
